"""Add Recipe model

Revision ID: 802ba2593dcc
Revises: c7374a0843eb
Create Date: 2026-01-12 12:29:15.552153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802ba2593dcc'
down_revision = 'c7374a0843eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    # ### end Alembic commands ###
